const quest = [
  {number:1,
  question:"Observe o algoritmo a seguir.<br><img src='./img/variables.png'/><br><br>O que faz a segunda linha desse algoritmo?",
  alternative1:"Criar uma variável chamada 'a' e colocar o valor inteiro 39 nela",
  alternative2:"Criar uma variável chamada 'b' e colocar o valor inteiro 3 nela",
  alternative3:"Criar uma variável chamada 'b' e colocar o valor booleano 3 nela",
  alternative4:"Criar uma variável chamada 'c' e colocar o valor inteiro 3 nela",
  correctAlternative:"75a"},
  {number:2,
  question:"Observe o algoritmo a seguir.<br><img src='./img/variables.png'/><br><br>O que faz a terceira linha desse algoritmo?",
  alternative1:"Criar uma variável chamada 'a' e colocar o valor da variável 'b' nela",
  alternative2:"Criar uma variável chamada 'c' e colocar a soma dos valores das variáveis 'a' e 'b' nela",
  alternative3:"Criar uma variável chamada 'c' e colocar o valor de ponto flutuante 3 nela",
  alternative4:"Criar uma variável chamada 'c' e colocar a divisão dos valores das variáveis 'a' e 'b' nela",
  correctAlternative:"7af"},
  {number:3,
  question:"Observe o algoritmo a seguir.<br><img src='./img/if.png'/><br><br>Qual é o objetivo da primeira linha desse algoritmo?",
  alternative1:"Imprime uma mensagem",
  alternative2:"Espera o usuário digitar uma entrada (espera-se que seja um número)",
  alternative3:"Imprime uma mensagem e espera o usuário digitar uma entrada (espera-se que seja um número)",
  alternative4:"Nenhuma das alternativas",
  correctAlternative:"786"},
  {number:4,
  question:"Observe o algoritmo a seguir.<br><img src='./img/if.png'/><br><br>Qual é o objetivo da terceira linha desse algoritmo?",
  alternative1:"Checa se a variável \"idade\" é menor que 18 ou não",
  alternative2:"Transforma a variável \"idade\" em um número inteiro",
  alternative3:"Checa se a variável \"idade\" é menor ou igual a 18",
  alternative4:"Imprime uma mensagem",
  correctAlternative:"733"},
  {number:5,
  question:"Observe o algoritmo a seguir.<br><img src='./img/if.png'/><br><br>Qual é o objetivo da quarta linha desse algoritmo?",
  alternative1:"Cria uma variável e insere o valor da subtração de 18 e \"idade\"",
  alternative2:"Cria uma variável e insere o valor da multiplicação de 18 e \"idade\"",
  alternative3:"Cria uma variável e insere o valor 18",
  alternative4:"Cria uma variável e insere o valor de \"idade\"",
  correctAlternative:"734"},
  {number:6,
  question:"Observe o algoritmo a seguir.<br><img src='./img/if.png'/><br><br>Qual é o objetivo da sexta linha desse algoritmo?",
  alternative1:"Nenhuma das alternativas",
  alternative2:"Else significa senão. Esta linha indica o bloco de código que deve ser executado se a \"idade\" for maior que 18",
  alternative3:"Else significa senão. Esta linha indica o bloco de código que deve ser executado se a \"idade\" for menor que 18",
  alternative4:"Else significa senão. Esta linha indica o bloco de código que deve ser executado caso a condição da linha 3 seja falsa",
  correctAlternative:"7b3"},
  {number:7,
  question:"Observe o algoritmo a seguir.<br><img src='./img/if.png'/><br><br>Qual será o resultado desse algoritmo se o usuário inserir o valor 12?",
  alternative1:"Você é menor de idade e faltam 6 anos para você fazer 18.",
  alternative2:"Você é menor de idade e faltam 5 anos para você fazer 18.",
  alternative3:"Você é maior de idade.",
  alternative4:"Você é menor de idade e faltam faltaPara18 anos para você fazer 18.",
  correctAlternative:"736"},
  {number:8,
  question:"Observe o algoritmo a seguir.<br><img src='./img/if.png'/><br><br>Qual será o resultado desse algoritmo se o usuário inserir o valor 42?",
  alternative1:"Você é menor de idade e faltam 6 anos para você fazer 18.",
  alternative2:"Você é menor de idade e faltam 5 anos para você fazer 18.",
  alternative3:"Você é maior de idade.",
  alternative4:"Você é menor de idade e faltam faltaPara18 anos para você fazer 18.",
  correctAlternative:"78b"},
  {number:9,
  question:"O que o algoritmo a seguir faz? <br><br><img src='./img/fibonacci.png'/><br>",
  alternative1:"Calcula e imprime o fatorial de 13 (13!)",
  alternative2:"Calcula e imprime o fatorial de 13 (10!)",
  alternative3:"Calcula e imprime os primeiros 13 números da sequência de Fibonacci",
  alternative4:"Calcula e imprime os primeiros 10 números da sequência de Fibonacci",
  correctAlternative:"78c"},
  {number:10,
  question:"O que o algoritmo a seguir faz? <br><br><img src='./img/simpleloop.png'/><br>",
  alternative1:"Imprime os números inteiros de 1 a 5",
  alternative2:"Imprime os números inteiros de 0 a 4",
  alternative3:"Imprime a letra \"i\" 5 vezes",
  alternative4:"Calcula e imprime os primeiros 10 números da sequência de Fibonacci",
  correctAlternative:"763"},
  {number:11,
  question:"O que o algoritmo a seguir faz? <br><br><img src='./img/simpleloop2.png'/><br>",
  alternative1:"Imprime os números inteiros de 1 a 3",
  alternative2:"Imprime \"Du-Du-Du\"",
  alternative3:"Imprime \"Du\" 3 vezes",
  alternative4:"Imprime os números inteiros de 0 a 2",
  correctAlternative:"78e"},
  {number:12,
  question:"O que o algoritmo a seguir faz? <br><br><img src='./img/simpleloop3.png'/><br>",
  alternative1:"Imprime a letra \"F\" 1 vez e depois a letra \"H\" 3 vezes",
  alternative2:"Imprime a palavra \"FHHH\"",
  alternative3:"Imprime a palavra \"FFF\"",
  alternative4:"Imprime a letra \"F\" 3 vezes",
  correctAlternative:"765"},
  {number:13,
  question:"Este algoritmo a seguir é uma função. O que esta função faz? <br><br><img src='./img/funcaosoma.png'/><br>",
  alternative1:"Realiza a soma dos valores das duas variáveis \"a\" e \"b\". Sejam elas números ou letras.",
  alternative2:"Realiza a soma dos valores das duas variáveis \"a\" e \"b\", somente se elas forem números",
  alternative3:"Realiza a soma dos valores das duas variáveis \"a\" e \"b\", somente se elas forem letras (o que podemos também chamar de concatenação)",
  alternative4:"Devolve a palavra \"a+b\"",
  correctAlternative:"73c"},
  {number:14,
  question:"Este algoritmo a seguir é uma função. Qual é o nome dessa função? <br><br><img src='./img/funcaosoma.png'/><br>",
  alternative1:"\"soma\"",
  alternative2:"\"def soma\"",
  alternative3:"\"somas()\"",
  alternative4:"\"somar\"",
  correctAlternative:"73d"},
  {number:15,
  question:"Este algoritmo a seguir é uma função. Quantos parâmetros esta função possui? <br><br><img src='./img/funcaosoma.png'/><br>",
  alternative1:"1",
  alternative2:"2",
  alternative3:"3",
  alternative4:"4",
  correctAlternative:"768"},
  {number:16,
  question:"Este algoritmo a seguir é uma função. O que esta função faz? <br><br><img src='./img/funcaopotencia.png'/><br>",
  alternative1:"Calcula a potência de \"a\" elevado a \"b\"",
  alternative2:"Calcula a multiplicação de \"a\" e \"b\"",
  alternative3:"Imprime uma palavra com várias repetições de \"a\"",
  alternative4:"Calcula e imprime os primeiros \"b\" números da sequência de Fibonacci",
  correctAlternative:"73f"},
  {number:17,
  question:"Este algoritmo a seguir é uma função. <br><img src='./img/funcaopotencia.png'/><br><br> Escolha a alternativa com a correta utilização da função e o resultado esperado.",
  alternative1:"pot(3,3) <br> 9",
  alternative2:"def pot(3,3) <br> 27",
  alternative3:"pot(3,3) <br> 27",
  alternative4:"pot(3,3) <br> aaa",
  correctAlternative:"794"},
  {number:18,
  question:"Observe o algoritmo a seguir.<br><img src='./img/inputprint.png'/><br><br> O que podemos dizer sobre este algoritmo?",
  alternative1:"O algoritmo utiliza 2 funções nativas do python. Uma chamada \"input\" e outra chamada \"print\"",
  alternative2:"O algoritmo utiliza 3 funções nativas do python. Uma chamada \"input\", outra chamada \"print\" e outra chamada \"nome\"",
  alternative3:"O algoritmo utiliza 1 função nativa do python, chamada \"input\"",
  alternative4:"O algoritmo não utiliza nenhuma função nativa",
  correctAlternative:"741"},
  {number:19,
  question:"O algoritmo a seguir possui só uma linha, na qual é criada uma variável e nesta variável é inserida o resultado das operações matemáticas.<br><img src='./img/ordemoperacoes.png'/><br><br> Qual valor será adicionado na variável \"x\"?",
  alternative1:"20",
  alternative2:"14",
  alternative3:"13",
  alternative4:"6",
  correctAlternative:"796"}
]
